export const PLANS = [
    {
        id: 'free',
        label: 'Free',
        tagline: 'Forever free',
        monthlyPrice: 0,
        annualPrice: null,
        highlighted: false,
    },
    {
        id: 'starter',
        label: 'Starter',
        tagline: 'Save 20% annually',
        monthlyPrice: 499,
        annualPrice: 4799,
        highlighted: false,
    },
    {
        id: 'pro',
        label: 'Pro',
        tagline: 'Most popular',
        monthlyPrice: 999,
        annualPrice: 9599,
        highlighted: true,
    },
    {
        id: 'enterprise',
        label: 'Enterprise',
        tagline: 'For large teams & enterprises',
        monthlyPrice: 1999,
        annualPrice: 19199,
        highlighted: false,
    },
]

export const PLAN_FEATURES = {
    free: {
        workspaces: 1,
        teamMembers: 1,
        monthlyTransactions: 50,
        dataRecords: 25,
        customWorkflows: 5,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: false,
        pdfExcelExport: false,
        advancedAnalytics: false,
        multiWorkspaceDashboard: false,
        rbac: false,
        twoFA: false,
        supportLevel: 'community',
        dataRetentionMonths: 3,
    },
    starter: {
        workspaces: 1,
        teamMembers: 3,
        monthlyTransactions: 500,
        dataRecords: 200,
        customWorkflows: 25,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: true,
        pdfExcelExport: true,
        advancedAnalytics: false,
        multiWorkspaceDashboard: false,
        rbac: false,
        twoFA: false,
        supportLevel: 'email',
        dataRetentionMonths: 6,
    },
    pro: {
        workspaces: 3,
        teamMembers: 10,
        monthlyTransactions: Infinity,
        dataRecords: Infinity,
        customWorkflows: Infinity,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: true,
        pdfExcelExport: true,
        advancedAnalytics: true,
        multiWorkspaceDashboard: true,
        rbac: true,
        twoFA: true,
        supportLevel: 'priority',
        dataRetentionMonths: 12,
    },
    enterprise: {
        workspaces: Infinity,
        teamMembers: Infinity,
        monthlyTransactions: Infinity,
        dataRecords: Infinity,
        customWorkflows: Infinity,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: true,
        pdfExcelExport: true,
        advancedAnalytics: true,
        multiWorkspaceDashboard: true,
        rbac: true,
        twoFA: true,
        supportLevel: 'csm',
        dataRetentionMonths: Infinity,
    },
}
