export const PLANS = [
    {
        id: 'free',
        label: 'Free',
        tagline: 'Forever free',
        monthlyPrice: 0,
        annualPrice: null,
        highlighted: false,
    },
    {
        id: 'starter',
        label: 'Starter',
        tagline: 'Save 20% annually',
        monthlyPrice: 499,
        annualPrice: 4799,
        highlighted: false,
    },
    {
        id: 'pro',
        label: 'Pro',
        tagline: 'Most popular',
        monthlyPrice: 999,
        annualPrice: 9599,
        highlighted: true,
    },
    {
        id: 'enterprise',
        label: 'Enterprise',
        tagline: 'For chains & franchises',
        monthlyPrice: 1999,
        annualPrice: 19199,
        highlighted: false,
    },
]

export const PLAN_LIMITS = {
    free: {
        outlets: 1,
        staffAccounts: 1,
        monthlyBills: 50,
        inventoryItems: 25,
        menuItems: 15,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: false,
        pdfExcelExport: false,
        advancedAnalytics: false,
        multiOutletDashboard: false,
        rbac: false,
        twoFA: false,
        supportLevel: 'community',
        dataRetentionMonths: 3,
    },
    starter: {
        outlets: 1,
        staffAccounts: 3,
        monthlyBills: 500,
        inventoryItems: 200,
        menuItems: 100,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: true,
        pdfExcelExport: true,
        advancedAnalytics: false,
        multiOutletDashboard: false,
        rbac: false,
        twoFA: false,
        supportLevel: 'email',
        dataRetentionMonths: 6,
    },
    pro: {
        outlets: 3,
        staffAccounts: 10,
        monthlyBills: Infinity,
        inventoryItems: Infinity,
        menuItems: Infinity,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: true,
        pdfExcelExport: true,
        advancedAnalytics: true,
        multiOutletDashboard: true,
        rbac: true,
        twoFA: true,
        supportLevel: 'priority',
        dataRetentionMonths: 12,
    },
    enterprise: {
        outlets: Infinity,
        staffAccounts: Infinity,
        monthlyBills: Infinity,
        inventoryItems: Infinity,
        menuItems: Infinity,
        offlineMode: true,
        gstBilling: true,
        attendancePayroll: true,
        pdfExcelExport: true,
        advancedAnalytics: true,
        multiOutletDashboard: true,
        rbac: true,
        twoFA: true,
        supportLevel: 'csm',
        dataRetentionMonths: Infinity,
    },
}
